### ISSUE TITLE
Sporadically not working

### ISSUE THREAD

**Issue by vespertine1259** [gaffling/PHP-Grab-Google-Reviews#12]
For me, the same code seems to not always be working. E.g. currently, without a change in the code, I get no reviews. If I try your exact code, I also don't get any reviews from the Baker Street Bistro. I had similar issues in the past, where it starting working, usually after half a day or so. Am I the only one experiencing this or is Google changing something there?
Thanks a lot for a response!

**Comment by vespertine1259** [comment]
Haha, minutes after posting it works again. I have no idea why, again no change in the code.

**Comment by gaffling** [comment]
Maybe you "testet" to much an Google blocked your IP for a while ?!
