### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by markosole** [gaffling/PHP-Grab-Google-Reviews#14]
Hi @gaffling  thanks for making this and sharing with us. I've just implemented it and works just fine. 
Except there is no error handling for cUrl check and I did not know what's going on until I've opened error_log.

I would like to suggest two major features:

1. Check if cUrl is enabled and show error if not

I'll add those on my project, but would be nice to have it available for others.

**Comment by gaffling** [comment]
improved it - thanks for the hint

**Comment by markosole** [comment]
@gaffling no worries :) Thanks
