### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by ibahcivan** [gaffling/PHP-Grab-Google-Reviews#17]
Hello, 

i want to use your code, but it don't work.
I get a reviews.json file with an error message:

{
   "error_message" : "API keys with referer restrictions cannot be used with this API.",
   "html_attributions" : [],
   "status" : "REQUEST_DENIED"
}

I think the API key is set up incorrectly. Can you tell me how exactly to set it up correctly?

**Comment by gaffling** [comment]
The API Key is not correctly set up - google "API keys with referer restrictions cannot be used with this API."
