### ISSUE TITLE
Auto translate in prod

### ISSUE THREAD

**Issue by jaopedro-cs** [gaffling/PHP-Grab-Google-Reviews#4]
The review auto translate in prod, but not in development:

![image](https://user-images.githubusercontent.com/34106759/85823011-aa43e900-b752-11ea-8c29-30a5c4c516d8.png)

**Comment by mahotilo** [comment]
I have solved this problem by adding
such kind of request option
`	curl_setopt($ch, CURLOPT_HTTPHEADER, array("Accept-Language: en"));`
before
https://github.com/gaffling/PHP-Grab-Google-Reviews/blob/5fc265a99803e7ed4b689d4838096e46c76bfd65/get-reviews.php#L51

UPD
Thus, you can define the review output language and prevent automatic translation from Google
