### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by sharoncreech** [gaffling/PHP-Grab-Google-Reviews#9]
It works great. Thank you. 

I do not have any issue but it would be nice if you could consider in future as option to add:
-  a picture (avatar of customer) next to the name in the options,
-  if we could choose how many reviews to be visible instead of by default 8 
-  if we could add an option vertically / horizontally display of reviews.

**Integrating schema.org Rating  by stars into code** would make the completeness of this project

**Comment by mahotilo** [comment]
> a picture (avatar of customer) next to the name in the options,

It is possible out of the box
> if we could choose how many reviews to be visible instead of by default 8

Sorry, it is not possible
> if we could add an option vertically / horizontally display of reviews.

You can control it via CSS.

**Comment by sharoncreech** [comment]
Thanks for reply.

What about 'Integrating schema.org Rating by stars into code' as it is very important factor for search engine.

**Comment by mahotilo** [comment]
@sharoncreech 
I am terribly sorry, my comment was not based on the current brunch, but on my fork. So the proposal for the avatar is relevant.

**Comment by mahotilo** [comment]
@gaffling 
I have created the PR https://github.com/gaffling/PHP-Grab-Google-Reviews/pull/10 for an avatar option.
> a picture (avatar of customer) next to the name in the options,

Since my fork is too far from the current master, I have not tested it. Excuse me.

**Comment by mahotilo** [comment]
@gaffling
Another PR https://github.com/gaffling/PHP-Grab-Google-Reviews/pull/11 for 

> if we could choose how many reviews to be visible instead of by default 8

**Comment by sharoncreech** [comment]
Thanks.

What about 'Integrating schema.org Rating or Review by stars into code' rich result ? Something like this 
`for ($i=1; $i <= $review[4]; ++$i) {if($i > 1){break;}} $return .= '<itemprop="reviewRating" itemscope itemtype="http://schema.org/Rating"> <meta itemprop="worstRating" content="1"/><meta itemprop="bestRating" content="5"/> <meta itemprop="ratingValue" content="'.$review[4].'" />';  `

Validating https://search.google.com/test/rich-results

**Comment by mahotilo** [comment]
I do not quite understand if there is a reason to give back to Google reviews from Google?
In my opinion, such a schema should be used to allow Goggle to find reviews on my page that originated from my own script or other sources. Not from Google itself. Am I wrong?

**Comment by sharoncreech** [comment]
I thought it will be cool to have it and got it so far to works with modifying codes but then come behind that Google does not support all schemas as in past.  Only specific. So for example `content="http://schema.org/WebContent"` is valid but not anymore supported by Google (:

Thanks
